import { useEffect, useState } from "react";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import {
  PieChart,
  Pie,
  Cell,
  Tooltip,
  Legend,
  ResponsiveContainer,
} from "recharts";

const Reports = () => {
  const [period, setPeriod] = useState("weekly");
  const [report, setReport] = useState(null);
  const [loading, setLoading] = useState(false);
  const [currentPage, setCurrentPage] = useState(1);
  const [isMobile, setIsMobile] = useState(window.innerWidth < 640);
  const recordsPerPage = 10;

  useEffect(() => {
    setCurrentPage(1);
    fetchReport();
  }, [period]);

  useEffect(() => {
  const handleResize = () => {
    setIsMobile(window.innerWidth < 640);
  };

  window.addEventListener("resize", handleResize);

  return () => {
    window.removeEventListener("resize", handleResize);
  };
}, []);


  const fetchReport = async () => {
    try {
      setLoading(true);

      const token = localStorage.getItem("adminToken");

      const response = await fetch(
        `${import.meta.env.VITE_API_URL}/admin/reports?period=${period}`,
        {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        }
      );

      const data = await response.json();

      if (data.success) {
        setReport(data);
      }
    } catch (error) {
      console.error("Report Fetch Error:", error);
    } finally {
      setLoading(false);
    }
  };

  const downloadPDF = () => {
    if (!report) return;

    const doc = new jsPDF();

    doc.setFontSize(18);
    doc.setFont("helvetica", "bold");
    doc.text("SLTMobitel Internal Audit Unit (IAU)", 14, 20);

    doc.setFontSize(14);
    doc.text("Complaint Management Portal", 14, 30);

    doc.setFontSize(12);
    doc.setFont("helvetica", "normal");
    doc.text("Operational Report", 14, 38);

    doc.line(14, 42, 195, 42);

    const today = new Date().toLocaleDateString();

    doc.text(`Generated Date : ${today}`, 14, 52);
    doc.text(`Report Period : ${period}`, 14, 60);

    doc.setFont("helvetica", "bold");
    doc.text("Executive Summary", 14, 75);

    doc.setFont("helvetica", "normal");

    doc.text(
      `Total Complaints : ${report.summary.totalComplaints}`,
      20,
      85
    );

    doc.text(
      `Submitted : ${report.summary.submitted}`,
      20,
      95
    );

    doc.text(
     `Preliminary Review : ${report.summary.preliminaryReview}`,
     20,
     105
    );

    doc.text(
      `Under Investigation : ${report.summary.underInvestigation}`,
      20,
      115
    );

    doc.text(
     `Awaiting Evidence : ${report.summary.awaitingEvidence}`,
     20,
     125
    );

    doc.text(
     `Escalated to CIABOC : ${report.summary.escalated}`,
     20,
     135
    );

    doc.text(
      `Resolved : ${report.summary.resolved}`,
      20,
      145
    );

    doc.text(
     `Closed : ${report.summary.closed}`,
     20,
     155
    );

    autoTable(doc, {
      startY: 170,
      head: [["CRN", "Category", "Status", "Date Submitted"]],
      body: report.complaints.map((item) => [
        item.crn,
        item.category,
        item.currentStatus,
        new Date(item.createdAt).toLocaleDateString(),
      ]),
    });

    const finalY = doc.lastAutoTable.finalY + 20;

    doc.setFontSize(10);

    doc.text("Generated by IAU Complaint Portal", 14, finalY);

    doc.text(
      "Confidential Document - Internal Use Only",
      14,
      finalY + 8
    );

    doc.save(`IAU_Operational_Report_${period}.pdf`);
  };

  const getStatusColor = (status) => {
    switch (status) {
      case "Resolved":
        return "bg-green-100 text-green-700";
      case "Under Investigation":
        return "bg-yellow-100 text-yellow-700";
      case "Submitted":
        return "bg-blue-100 text-blue-700";
      case "Awaiting Evidence":
        return "bg-orange-100 text-orange-700";
      default:
        return "bg-gray-100 text-gray-700";
    }
  };

  const indexOfLastRecord =
      currentPage * recordsPerPage;

  const indexOfFirstRecord =
       indexOfLastRecord - recordsPerPage;

  const currentRecords =
       report?.complaints.slice(
         indexOfFirstRecord,
         indexOfLastRecord
       ) || [];

  const totalPages = report
      ? Math.ceil(
         report.complaints.length / recordsPerPage
      )
      : 1;


  const chartData = report
    ? [
        {
          name: "Submitted",
          value: report.summary.submitted,
        },

        {
        name: "Preliminary Review",
        value: report.summary.preliminaryReview,
        },

        {
        name: "Under Investigation",
        value: report.summary.underInvestigation,
        },

        {
        name: "Awaiting Evidence",
        value: report.summary.awaitingEvidence,
        },

        {
        name: "Escalated to CIABOC",
        value: report.summary.escalated,
        },
        
        {
          name: "Resolved",
          value: report.summary.resolved,
        },

        {
        name: "Closed",
        value: report.summary.closed,
        },
        
      ]
    : [];

  return (
    <div className="p-3 sm:p-4 md:p-6">
      <h1 className="text-xl sm:text-2xl font-bold mb-4 sm:mb-6">
        Complaint Reports
      </h1>

      <div className="flex flex-col md:flex-row gap-3 mb-6">
        <select
          value={period}
          onChange={(e) => setPeriod(e.target.value)}
          className="border p-2 rounded w-full md:w-auto"
        >
          <option value="2days">Last 2 Days</option>
          <option value="weekly">Last 7 Days</option>
          <option value="2weekly">Last 14 Days</option>
          <option value="monthly">Last 30 Days</option>
        </select>

        <button
          onClick={downloadPDF}
          className="bg-green-600 hover:bg-green-700 text-white px-4 py-2 rounded font-medium w-full md:w-auto"
        >
          Download PDF
        </button>
      </div>

      {loading ? (
        <div className="text-center py-10">
          Loading Report...
        </div>
      ) : (
        report && (
          <>
            {/* Summary Cards */}
            {/* Complaint Status Summary */}

<div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-4 mb-6">

  <div className="bg-blue-50 p-4 rounded shadow text-center">
    <h3>Total Complaints</h3>
    <p className="text-2xl sm:text-3xl font-bold">
      {report.summary.totalComplaints}
    </p>
  </div>

  <div className="bg-cyan-50 p-4 rounded shadow text-center">
    <h3>Submitted</h3>
    <p className="text-2xl sm:text-3xl font-bold">
      {report.summary.submitted}
    </p>
  </div>

  <div className="bg-purple-50 p-4 rounded shadow text-center">
    <h3>Preliminary Review</h3>
    <p className="text-2xl sm:text-3xl font-bold">
      {report.summary.preliminaryReview}
    </p>
  </div>

  <div className="bg-yellow-50 p-4 rounded shadow text-center">
    <h3>Under Investigation</h3>
    <p className="text-2xl sm:text-3xl font-bold">
      {report.summary.underInvestigation}
    </p>
  </div>

  <div className="bg-orange-50 p-4 rounded shadow text-center">
    <h3>Awaiting Evidence</h3>
    <p className="text-2xl sm:text-3xl font-bold">
      {report.summary.awaitingEvidence}
    </p>
  </div>

  <div className="bg-red-50 p-4 rounded shadow text-center">
    <h3>Escalated to CIABOC</h3>
    <p className="text-2xl sm:text-3xl font-bold">
      {report.summary.escalated}
    </p>
  </div>

  <div className="bg-green-50 p-4 rounded shadow text-center">
    <h3>Resolved</h3>
    <p className="text-2xl sm:text-3xl font-bold">
      {report.summary.resolved}
    </p>
  </div>

  <div className="bg-gray-50 p-4 rounded shadow text-center">
    <h3>Closed</h3>
    <p className="text-2xl sm:text-3xl font-bold">
      {report.summary.closed}
    </p>
  </div>

</div>




          {/* Additional Statistics */}
<div className="mb-6">
  <h2 className="text-lg font-bold mb-4">
    Additional Statistics
  </h2>

  <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">

    <div className="bg-purple-50 p-4 rounded shadow text-center">
      <h3>Anonymous Complaints</h3>
      <p className="text-2xl sm:text-3xl font-bold">
        {report.summary.anonymousComplaints}
      </p>
    </div>

    <div className="bg-indigo-50 p-4 rounded shadow text-center">
      <h3>Named Complaints</h3>
      <p className="text-2xl sm:text-3xl font-bold">
        {report.summary.namedComplaints}
      </p>
    </div>

    <div className="bg-orange-50 p-4 rounded shadow text-center">
      <h3>Evidence Files</h3>
      <p className="text-2xl sm:text-3xl font-bold">
        {report.summary.totalEvidence}
      </p>
    </div>

  </div>
</div>





            {/* Pie Chart */}
            <div className="bg-white p-3 sm:p-6 rounded shadow mb-6">
              <h2 className="text-lg font-bold mb-4">
                Complaint Status Distribution
              </h2>

              <ResponsiveContainer width="100%" height={isMobile ? 420 : 350}>
                <PieChart>
                  <Pie
                    data={chartData}
                    dataKey="value"
                    nameKey="name"
                    outerRadius={isMobile ? 60 : 120}
                    label={!isMobile}
                  >
                   
                    <Cell fill="#2563EB" /> {/* Submitted */}
                    <Cell fill="#F59E0B" /> {/* Preliminary Review */}
                    <Cell fill="#10B981" /> {/* Under Investigation */}
                    <Cell fill="#EF4444" /> {/* Awaiting Evidence */}
                    <Cell fill="#8B5CF6" /> {/* Escalated */}
                    <Cell fill="#06B6D4" /> {/* Resolved */}
                    <Cell fill="#6B7280" /> {/* Closed */}

                  </Pie>

                  <Tooltip />
                  <Legend 
                     verticalAlign="bottom"
                      align="center"
                      wrapperStyle={{
                         fontSize: isMobile ? "11px" : "14px",
                         paddingTop: "10px",
                      }}
                  />
                  
                </PieChart>
              </ResponsiveContainer>
            </div>

            {/* Total Records */}
            <div className="mb-4 text-gray-600 font-medium">
              Total Records Found : {report.complaints.length}
            </div>

            {/* Table */}
            <div className="bg-white rounded shadow overflow-x-auto w-full">
              <table className="w-full min-w-[600px] text-sm">
                <thead>
                  <tr className="bg-gray-100">
                    <th className="p-3 text-left">CRN</th>
                    <th className="p-3 text-left">Category</th>
                    <th className="p-3 text-left">Status</th>
                    <th className="p-3 text-left">Date</th>
                  </tr>
                </thead>

                <tbody>
                  {report.complaints.length > 0 ? (
                    currentRecords.map((item) => (
                      <tr
                        key={item._id}
                        className="border-b hover:bg-gray-50"
                      >
                        <td className="p-3">{item.crn}</td>

                        <td className="p-3">
                          {item.category}
                        </td>

                        <td className="p-3">
                          <span
                            className={`px-3 py-1 rounded-full text-xs font-medium ${getStatusColor(
                              item.currentStatus
                            )}`}
                          >
                            {item.currentStatus}
                          </span>
                        </td>

                        <td className="p-3">
                          {new Date(
                            item.createdAt
                          ).toLocaleDateString()}
                        </td>
                      </tr>
                    ))
                  ) : (
                    <tr>
                      <td
                        colSpan="4"
                        className="text-center p-8 text-gray-500"
                      >
                        No complaints found for this period
                      </td>
                    </tr>
                  )}
                </tbody>
              </table>
            </div>



            <div className="flex flex-col sm:flex-row items-center justify-center gap-3 mt-6">
  <button
    onClick={() =>
      setCurrentPage((prev) =>
        Math.max(prev - 1, 1)
      )
    }
    disabled={currentPage === 1}
   className="w-full sm:w-auto px-4 py-2 bg-gray-200 rounded disabled:opacity-50"
  >
    Previous
  </button>

  <span className="font-medium">
    Page {currentPage} of {totalPages}
  </span>

  <button
    onClick={() =>
      setCurrentPage((prev) =>
        Math.min(prev + 1, totalPages)
      )
    }
    disabled={currentPage === totalPages}
    className="w-full sm:w-auto px-4 py-2 bg-gray-200 rounded disabled:opacity-50"
  >
    Next
  </button>
</div>
          </>
        )
      )}
    </div>
  );
};

export default Reports;